tmp cache

diff --git a/Dockerfile.kinetic b/Dockerfile.kinetic
--- a/Dockerfile.kinetic
+++ b/Dockerfile.kinetic
@@ -37,62 +37,62 @@ RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
     make install
 
 
-#### base ros pkg, they should be replaced by deb package
-WORKDIR ${WORKHOME}/base_ws
-RUN wstool init src && \
-    wstool set -y -t src hrpsys https://github.com/fkanehiro/hrpsys-base.git --git && \
-    wstool update -t src
-RUN rosdep install -y -r --from-paths src --ignore-src || echo 'Ignore rosdep error'
-
-# build hrpsys parallel ??
-WORKDIR ${WORKHOME}/base_ws
-RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build hrpsys --no-notify -DENABLE_DOXYGEN=OFF"
-RUN source ${WORKHOME}/base_ws/devel/setup.bash
-
-
-#### ros pkg
-WORKDIR ${WORKHOME}/catkin_ws
-
-## for travis
-RUN mkdir -p src/rtmros_choreonoid
-COPY . src/rtmros_choreonoid/
-
-# debug
-RUN ls src/rtmros_choreonoid/
-
-RUN wstool init --shallow src src/rtmros_choreonoid/depend.rosinstall && \
+# #### base ros pkg, they should be replaced by deb package
+# WORKDIR ${WORKHOME}/base_ws
 # RUN wstool init src && \
-#     wstool set -y -t src rtmros_tutorials https://github.com/start-jsk/rtmros_tutorials.git --git && \
-# # (for compiling...)   wstool set -y -t src rtmros_common https://github.com/start-jsk/rtmros_common --git && \
-#     wstool set -y -t src rtmros_common https://github.com/YoheiKakiuchi/rtmros_common --git -v fix_rtc_name2 && \
-# #    wstool set -y -t src jsk_common https://github.com/jsk-ros-pkg/jsk_common.git --git && \
-#     wstool set -y -t src pr2_navigation https://github.com/PR2/pr2_navigation.git --git && \
-# # (install)  wstool set -y -t src rtmros_choreonoid https://github.com/start-jsk/rtmros_choreonoid --git && \
-#     wstool update -t src && \
-#     git clone https://github.com/jsk-ros-pkg/jsk_robot.git src/jsk_robot && \
-# ## why?
-#     (cd src/jsk_robot; rm -rf README.md jsk_baxter_robot jsk_naoqi_robot jsk_robot doc jsk_fetch_robot jsk_pr2_robot) && \
-## remove hrpsys_gazebo, hironx, hrpsys, opnehrp3 tutorials because it cause to install ros-indigo-hrpsys
-    (cd src/rtmros_tutorials; rm -rf hrpsys_gazebo_tutorials hironx_tutorial hrpsys_tutorials openhrp3_tutorials)
+#     wstool set -y -t src hrpsys https://github.com/fkanehiro/hrpsys-base.git --git && \
+#     wstool update -t src
+# RUN rosdep install -y -r --from-paths src --ignore-src || echo 'Ignore rosdep error'
 
-#RUN rosdep install -y -r --from-paths src --ignore-src || echo 'Ignore rosdep error'
-RUN /bin/bash -c "source ${WORKHOME}/base_ws/devel/setup.bash && rosdep install -y -r --from-paths src --ignore-src || echo 'Ignore_rosdep_error'"
-
-## should be solved ...,  hrpsys-base, jsk_common, pr2_navigation ###
-# RUN apt-get install -q -qq -y ros-${ROS_DISTRO}-jsk-tilt-laser ros-${ROS_DISTRO}-jsk-recognition && \
-#     apt-get clean && \
-#     rm -rf /var/lib/apt/lists/
+# # build hrpsys parallel ??
+# WORKDIR ${WORKHOME}/base_ws
+# RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build hrpsys --no-notify -DENABLE_DOXYGEN=OFF"
+# RUN source ${WORKHOME}/base_ws/devel/setup.bash
 
 
-### build ros packages
-WORKDIR ${WORKHOME}/catkin_ws
-#RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build hrpsys_choreonoid_tutorials jsk_robot_startup pr2_navigation_self_filter --no-status --no-notify -j 1 -p 1"
-RUN /bin/bash -c "source ${WORKHOME}/base_ws/devel/setup.bash && catkin build hrpsys_choreonoid_tutorials jsk_robot_startup pr2_navigation_self_filter --no-status --no-notify"
+# #### ros pkg
+# WORKDIR ${WORKHOME}/catkin_ws
 
-##
-RUN /bin/bash -c "source ${WORKHOME}/catkin_ws/devel/setup.bash && rosrun roseus generate-all-msg-srv.sh geometry_msgs sensor_msgs hrpsys_ros_bridge opencv_apps"
+# ## for travis
+# RUN mkdir -p src/rtmros_choreonoid
+# COPY . src/rtmros_choreonoid/
+
+# # debug
+# RUN ls src/rtmros_choreonoid/
+
+# RUN wstool init --shallow src src/rtmros_choreonoid/depend.rosinstall && \
+# # RUN wstool init src && \
+# #     wstool set -y -t src rtmros_tutorials https://github.com/start-jsk/rtmros_tutorials.git --git && \
+# # # (for compiling...)   wstool set -y -t src rtmros_common https://github.com/start-jsk/rtmros_common --git && \
+# #     wstool set -y -t src rtmros_common https://github.com/YoheiKakiuchi/rtmros_common --git -v fix_rtc_name2 && \
+# # #    wstool set -y -t src jsk_common https://github.com/jsk-ros-pkg/jsk_common.git --git && \
+# #     wstool set -y -t src pr2_navigation https://github.com/PR2/pr2_navigation.git --git && \
+# # # (install)  wstool set -y -t src rtmros_choreonoid https://github.com/start-jsk/rtmros_choreonoid --git && \
+# #     wstool update -t src && \
+# #     git clone https://github.com/jsk-ros-pkg/jsk_robot.git src/jsk_robot && \
+# # ## why?
+# #     (cd src/jsk_robot; rm -rf README.md jsk_baxter_robot jsk_naoqi_robot jsk_robot doc jsk_fetch_robot jsk_pr2_robot) && \
+# ## remove hrpsys_gazebo, hironx, hrpsys, opnehrp3 tutorials because it cause to install ros-indigo-hrpsys
+#     (cd src/rtmros_tutorials; rm -rf hrpsys_gazebo_tutorials hironx_tutorial hrpsys_tutorials openhrp3_tutorials)
+
+# #RUN rosdep install -y -r --from-paths src --ignore-src || echo 'Ignore rosdep error'
+# RUN /bin/bash -c "source ${WORKHOME}/base_ws/devel/setup.bash && rosdep install -y -r --from-paths src --ignore-src || echo 'Ignore_rosdep_error'"
+
+# ## should be solved ...,  hrpsys-base, jsk_common, pr2_navigation ###
+# # RUN apt-get install -q -qq -y ros-${ROS_DISTRO}-jsk-tilt-laser ros-${ROS_DISTRO}-jsk-recognition && \
+# #     apt-get clean && \
+# #     rm -rf /var/lib/apt/lists/
 
 
-## ADD ./my_entrypoint.sh /
-## ENTRYPOINT ["/my_entrypoint.sh"]
-## CMD ["bash"]
+# ### build ros packages
+# WORKDIR ${WORKHOME}/catkin_ws
+# #RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build hrpsys_choreonoid_tutorials jsk_robot_startup pr2_navigation_self_filter --no-status --no-notify -j 1 -p 1"
+# RUN /bin/bash -c "source ${WORKHOME}/base_ws/devel/setup.bash && catkin build hrpsys_choreonoid_tutorials jsk_robot_startup pr2_navigation_self_filter --no-status --no-notify"
+
+# ##
+# RUN /bin/bash -c "source ${WORKHOME}/catkin_ws/devel/setup.bash && rosrun roseus generate-all-msg-srv.sh geometry_msgs sensor_msgs hrpsys_ros_bridge opencv_apps"
+
+
+# ## ADD ./my_entrypoint.sh /
+# ## ENTRYPOINT ["/my_entrypoint.sh"]
+# ## CMD ["bash"]
